import { StyleSheet } from "react-native";
import {
  FONT_DISPLAY_SERIF,
  FONT_TEXT_SERIF,
  FONT_UI_MEDIUM,
  FONT_UI_REGULAR,
} from "./mobileFonts";
import type { MobileNamedStyles } from "./mobileStyleTypes";

export const authStyles = {
  authScroll: { flex: 1 },
  authGuideContainer: {
    flexGrow: 1,
    width: "100%",
    minHeight: "100%",
    justifyContent: "center",
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  authGuideStage: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    minHeight: 360,
    justifyContent: "center",
  },
  authWelcomeBlock: {
    alignItems: "center",
    gap: 18,
    paddingVertical: 24,
  },
  authWelcomeBrand: {
    alignItems: "center",
    gap: 14,
  },
  authWelcomeLogo: {
    fontSize: 44,
    lineHeight: 52,
    letterSpacing: -1.2,
    fontFamily: FONT_DISPLAY_SERIF,
    fontWeight: "600",
  },
  authWelcomeTagline: {
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: -0.2,
    fontFamily: FONT_TEXT_SERIF,
  },
  authWelcomeCtaWrap: {
    marginTop: 32,
    alignItems: "center",
  },
  authPickBlock: {
    width: "100%",
    alignItems: "center",
    gap: 36,
    paddingVertical: 12,
  },
  authPickHeader: {
    width: "100%",
    alignItems: "center",
  },
  authTopBack: {
    position: "absolute",
    left: 8,
    zIndex: 30,
    elevation: 30,
  },
  authTopBackBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  authStepTitle: {
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.6,
    fontFamily: FONT_DISPLAY_SERIF,
    fontWeight: "600",
  },
  authStepTitleCenter: {
    textAlign: "center",
  },
  authModeOrbit: {
    width: "100%",
    alignItems: "center",
    gap: 22,
  },
  authModeOrbitItem: {
    width: "100%",
    alignItems: "center",
  },
  authModeChoice: {
    alignItems: "center",
    gap: 12,
    paddingVertical: 4,
    paddingHorizontal: 16,
  },
  authModeHalo: {
    width: 88,
    height: 88,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: "center",
    justifyContent: "center",
  },
  authModeChoiceTitle: {
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.2,
    fontFamily: FONT_UI_MEDIUM,
    textAlign: "center",
  },
  authFormBlock: {
    width: "100%",
    gap: 24,
    paddingVertical: 8,
  },
  authFormFields: {
    gap: 12,
  },
  authCloudScanBlock: {
    alignItems: "center",
    gap: 18,
    paddingTop: 8,
    paddingBottom: 4,
  },
  authHeroActionBtn: {
    minHeight: 56,
    minWidth: 168,
    paddingHorizontal: 36,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  authHeroActionBtnText: {
    fontSize: 17,
    lineHeight: 22,
    fontFamily: FONT_UI_MEDIUM,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  authSubtleLink: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  authSubtleLinkText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: FONT_UI_REGULAR,
  },
  authCompactBtn: {
    minHeight: 44,
    paddingHorizontal: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  authCompactBtnText: {
    fontSize: 15,
    lineHeight: 20,
    fontFamily: FONT_UI_MEDIUM,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  authConnectWrap: {
    alignItems: "center",
    gap: 14,
  },
  authConnectBtnWide: {
    minWidth: 132,
    paddingHorizontal: 36,
  },
  authScanAboveConnect: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  authGhostBack: {
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  authGhostBackText: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: FONT_UI_REGULAR,
  },
  authInlineStatus: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
    fontFamily: FONT_UI_REGULAR,
  },
  authUrlRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
    paddingLeft: 14,
    paddingRight: 8,
    gap: 8,
  },
  authInputUrl: {
    flex: 1,
    minHeight: 52,
    backgroundColor: "transparent",
    paddingHorizontal: 0,
    paddingVertical: 12,
    color: "#d4d4d4",
    fontSize: 16,
    fontFamily: FONT_UI_REGULAR,
  },
  authScanInlineBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  authScanIconFrame: {
    width: 16,
    height: 16,
    position: "relative",
  },
  authScanIconLt: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 6,
    height: 6,
    borderLeftWidth: 1.8,
    borderTopWidth: 1.8,
    borderColor: "#9da5b4",
  },
  authScanIconRt: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 6,
    height: 6,
    borderRightWidth: 1.8,
    borderTopWidth: 1.8,
    borderColor: "#9da5b4",
  },
  authScanIconLb: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: 6,
    height: 6,
    borderLeftWidth: 1.8,
    borderBottomWidth: 1.8,
    borderColor: "#9da5b4",
  },
  authScanIconRb: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 6,
    height: 6,
    borderRightWidth: 1.8,
    borderBottomWidth: 1.8,
    borderColor: "#9da5b4",
  },
  authDeviceOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 40,
  },
  authDeviceBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  authDeviceSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 28,
    gap: 4,
  },
  authDeviceTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: FONT_UI_MEDIUM,
    marginBottom: 10,
  },
  authDeviceRow: {
    paddingVertical: 14,
    gap: 2,
  },
  authDeviceName: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: FONT_UI_MEDIUM,
  },
  authDeviceMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONT_UI_REGULAR,
  },

  scannerSafe: {
    flex: 1,
    backgroundColor: "#d4d4d4",
  },
  scannerWrap: { flex: 1, backgroundColor: "#d4d4d4" },
  scannerCamera: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#d4d4d4",
  },
  scannerCameraPreview: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    elevation: 0,
  },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    elevation: 10,
  },
  scannerShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  scannerTopBar: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  scannerTopBtn: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.88)",
    shadowColor: "#d4d4d4",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  scannerAlbumBtn: {
    position: "absolute",
    right: 24,
    width: 44,
    height: 44,
    borderRadius: 999,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(32,32,32,0.62)",
    zIndex: 12,
    elevation: 12,
  },
  scannerAlbumBtnPressed: {
    opacity: 0.82,
  },
  scannerAlbumBtnGlass: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "transparent",
  },
  scannerModeBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 92,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 18,
    backgroundColor: "rgba(0,0,0,0.44)",
    zIndex: 1,
  },
  scannerModeText: {
    color: "#252526",
    fontSize: 18,
    lineHeight: 24,
    fontFamily: FONT_UI_MEDIUM,
    letterSpacing: 0.3,
  },
  scannerModeDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    marginTop: 7,
    backgroundColor: "#252526",
  },
} satisfies MobileNamedStyles;
