import { Platform, StyleSheet } from "react-native";
import {
  FONT_DISPLAY_SERIF,
  FONT_MIXED_BODY_MEDIUM,
  FONT_MIXED_BODY_REGULAR,
  FONT_TEXT_SERIF,
  FONT_TEXT_SERIF_SEMIBOLD,
  FONT_UI_MEDIUM,
  FONT_UI_REGULAR,
  HANDWRITTEN_TEXT_FONT,
} from "./mobileFonts";
import type { MobileNamedStyles } from "./mobileStyleTypes";

export const chatStyles = {
  topBar: {
    height: 48,
    paddingHorizontal: 16,
    paddingTop: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    overflow: "visible",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(65,54,38,0.08)",
  },
  notebookShell: {
    flex: 1,
    backgroundColor: "#f5f1e8",
    position: "relative",
  },
  notebookTrack: {
    flex: 1,
    flexDirection: "row",
  },
  notebookPageFrame: {
    flex: 1,
  },
  notebookMainPage: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#f8f5ee",
  },
  slideDrawerSurface: {
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: "rgba(65,54,38,0.12)",
  },
  slideDrawerSurfaceRight: {
    borderRightWidth: 0,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "rgba(65,54,38,0.12)",
  },
  slideDrawerContent: {
    flex: 1,
    backgroundColor: "#f5f1e8",
  },
  slideDrawerOverlay: {
    backgroundColor: "rgba(36,33,29,0.22)",
  },
  chatStageViewport: {
    flex: 1,
    minHeight: 0,
  },
  streamTopGlowTrack: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(58, 143, 130, 0.10)",
    overflow: "hidden",
    zIndex: 8,
    elevation: 8,
  },
  streamTopGlowSweep: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 220,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(58, 143, 130, 0.62)",
  },
  topSideSlot: { width: 58, height: 40, alignItems: "flex-start", justifyContent: "center", zIndex: 25 },
  topSideSlotRight: { width: 58, height: 40, alignItems: "flex-end", justifyContent: "center", zIndex: 25 },
  topNavButton: {
    width: 44,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    position: "relative",
    transform: [{ translateY: -5 }],
  },
  topNavGlyph: {
    opacity: 0.92,
    transform: [{ translateY: -2 }, { rotate: "-1.5deg" }],
  },
  topNavGlyphActive: {
    opacity: 1,
    transform: [{ translateY: -2 }, { rotate: "0deg" }],
  },
  topBrand: {
    position: "absolute",
    left: 78,
    right: 78,
    flexDirection: "column",
    alignItems: "center",
    gap: 0,
    top: Platform.OS === "android" ? 6 : 5,
  },
  topTitle: {
    fontSize: 20,
    color: "#24211d",
    fontWeight: "700",
    fontFamily: FONT_TEXT_SERIF_SEMIBOLD,
  },
  topTitleCompact: {
    fontSize: 15,
    lineHeight: 19,
    color: "#24211d",
    fontWeight: "600",
    fontFamily: FONT_UI_MEDIUM,
  },
  topWorkspaceText: {
    fontSize: 11,
    lineHeight: 14,
    color: "#8d826f",
    fontWeight: "500",
  },
  toolBtn: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "#eef1f5",
  },
  toolBtnImage: { width: 16, height: 16 },
  workspaceMask: {
    position: "absolute",
    top: 58,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 5,
    elevation: 5,
  },
  workspaceBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  workspacePanel: {
    marginTop: 8,
    marginHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d7e1ee",
    backgroundColor: "#fbfcfe",
    paddingHorizontal: 12,
    paddingVertical: 12,
    zIndex: 6,
    elevation: 8,
  },
  workspaceTitle: {
    color: "#2a3442",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  workspaceList: { flex: 1 },
  workspaceListContent: { paddingBottom: 8, gap: 8 },
  workspaceListItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e1e7f0",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  workspaceListItemActive: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#bfd5f4",
    backgroundColor: "#eaf2fc",
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  workspaceFolderIcon: {
    width: 24,
    height: 17,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#9fb6d8",
    backgroundColor: "#dce8f8",
    alignItems: "center",
    justifyContent: "center",
  },
  workspaceFolderIconActive: {
    width: 24,
    height: 17,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#7ea3d7",
    backgroundColor: "#cfe1f8",
    alignItems: "center",
    justifyContent: "center",
  },
  workspaceFolderTab: {
    position: "absolute",
    top: -4,
    left: 3,
    width: 10,
    height: 4,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    backgroundColor: "#c9daf3",
    borderWidth: 1,
    borderColor: "#9fb6d8",
  },
  workspaceFolderTabActive: {
    position: "absolute",
    top: -4,
    left: 3,
    width: 10,
    height: 4,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    backgroundColor: "#bad0ee",
    borderWidth: 1,
    borderColor: "#84a9da",
  },
  workspaceFolderBodyAccent: {
    position: "absolute",
    bottom: 3,
    width: 14,
    height: 2,
    borderRadius: 2,
    backgroundColor: "#b7cae5",
  },
  workspaceFolderBodyAccentActive: {
    position: "absolute",
    bottom: 3,
    width: 14,
    height: 2,
    borderRadius: 2,
    backgroundColor: "#7fa3d5",
  },
  workspaceItemTextWrap: { flex: 1, gap: 1 },
  workspaceItemTitle: { color: "#2f3d51", fontSize: 13, fontWeight: "600" },
  workspaceItemTitleActive: {
    color: "#1f4e86",
    fontSize: 13,
    fontWeight: "700",
  },
  workspaceItemPath: { color: "#7a8798", fontSize: 11 },
  chatStatusBar: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 6,
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
  },
  chatStatusText: {
    color: "#6f7c8f",
    fontSize: 12,
    lineHeight: 17,
    flex: 1,
  },
  chatStatusCopyBtn: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d9e1ec",
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "#f8fafc",
  },
  chatStatusCopyTxt: { color: "#536278", fontSize: 11, fontWeight: "600" },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "#eef1f5",
  },
  iconTxt: { color: "#394455", fontWeight: "700" },

  chatBodyWrap: { flex: 1, paddingHorizontal: 14, position: "relative" },
  chatListStage: { flex: 1, position: "relative" },
  sessionSwitchOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 24,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 14,
    backgroundColor: "rgba(248, 246, 241, 0.92)",
  },
  blankWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingTop: 18,
  },
  blankHero: {
    alignSelf: "center",
    gap: 12,
  },
  blankEyebrow: {
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    fontFamily: FONT_UI_MEDIUM,
  },
  blankTitle: {
    fontSize: 27,
    lineHeight: 31,
    color: "#24211d",
    fontFamily: FONT_DISPLAY_SERIF,
    letterSpacing: -0.6,
    maxWidth: "100%",
  },
  blankSub: {
    color: "#8d826f",
    fontSize: 13.5,
    lineHeight: 21,
    fontFamily: FONT_TEXT_SERIF,
    maxWidth: "88%",
  },
  sessionSwitchWrap: {
    justifyContent: "center",
  },
  sessionSwitchHero: {
    gap: 14,
  },
  sessionSwitchTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontFamily: FONT_TEXT_SERIF_SEMIBOLD,
    letterSpacing: -0.3,
  },
  sessionSwitchRail: {
    height: 4,
    borderRadius: 999,
    borderWidth: 1,
    overflow: "hidden",
    marginTop: 2,
  },
  sessionSwitchRailFill: {
    width: "38%",
    height: "100%",
    borderRadius: 999,
    opacity: 0.82,
  },

  latestJumpBtn: {
    position: "absolute",
    bottom: 14,
    alignSelf: "center",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(65,54,38,0.10)",
    backgroundColor: "rgba(255,253,247,0.96)",
    shadowColor: "#503c1e",
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  latestJumpTxt: {
    color: "#3a352e",
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 24,
  },
  turnWrap: { width: "100%", alignSelf: "stretch", gap: 12 },
  historyOverlay: {
    position: "absolute",
    top: 6,
    left: 0,
    right: 0,
    alignItems: "center",
    gap: 6,
  },
  historyOverlayRail: {
    width: "46%",
    maxWidth: 176,
    height: 2,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(65,54,38,0.08)",
  },
  historyOverlayFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(86,77,63,0.58)",
  },
  historyOverlayFillActive: {
    width: "100%",
  },
  historyOverlayHint: {
    color: "#8b6c45",
    fontSize: 11,
    lineHeight: 14,
    fontFamily: FONT_UI_MEDIUM,
    backgroundColor: "rgba(255,253,247,0.82)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  historyHintWrap: { alignItems: "center", paddingTop: 4, paddingBottom: 2 },
  historyHintText: { color: "#7c8aa0", fontSize: 12 },
  thinkWrap: { width: "100%", alignItems: "flex-start" },
  contextWrap: { width: "100%", alignItems: "flex-start", paddingVertical: 1 },
  todoInlineWrap: { width: "100%", alignItems: "flex-start" },
  dividerWrap: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 2,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: "#ded6ca" },
  dividerLabel: { color: "#9a9182", fontSize: 11 },
  errorWrap: { width: "100%", alignItems: "flex-start" },
  todoInlineCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(65,54,38,0.10)",
    backgroundColor: "#fffdf7",
    paddingVertical: 12,
    paddingHorizontal: 13,
    gap: 12,
    shadowColor: "#503c1e",
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 1,
  },
  todoInlineCardCompact: {
    width: "100%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(65,54,38,0.10)",
    backgroundColor: "#fffdf7",
    paddingVertical: 12,
    paddingHorizontal: 13,
    gap: 12,
  },
  todoCardHead: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  todoCardHeadCompact: { flexDirection: "row", alignItems: "center", gap: 10 },
  todoCardHeadMain: { flex: 1, gap: 7 },
  todoTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  todoTitle: {
    color: "#24211d",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  todoActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 4,
  },
  todoChipRunning: {
    minWidth: 42,
    height: 21,
    borderRadius: 999,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e7f2ee",
    borderWidth: 1,
    borderColor: "#c8ded7",
  },
  todoChipRunningText: { color: "#2f7f74", fontSize: 11, fontWeight: "800" },
  todoChipDone: {
    minWidth: 42,
    height: 21,
    borderRadius: 999,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1eadf",
    borderWidth: 1,
    borderColor: "#ddd4c5",
  },
  todoChipDoneText: { color: "#5d5345", fontSize: 11, fontWeight: "800" },
  todoSummary: {
    color: "#7c766c",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  todoProgressTrack: {
    height: 5,
    borderRadius: 999,
    backgroundColor: "#e5ded2",
    overflow: "hidden",
  },
  todoProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#3a8f82",
  },
  todoChevron: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "0deg" }],
  },
  todoChevronCollapsed: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-90deg" }],
  },
  todoChevronLineLeft: {
    position: "absolute",
    width: 6,
    height: 1.5,
    borderRadius: 999,
    backgroundColor: "#8d826f",
    transform: [{ translateX: -1.5 }, { rotate: "45deg" }],
  },
  todoChevronLineRight: {
    position: "absolute",
    width: 6,
    height: 1.5,
    borderRadius: 999,
    backgroundColor: "#8d826f",
    transform: [{ translateX: 1.5 }, { rotate: "-45deg" }],
  },
  todoCloseBtn: {
    width: 22,
    height: 22,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3eee5",
    marginLeft: 4,
  },
  todoCloseText: {
    color: "#8d826f",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: -1,
  },
  todoToggleBtn: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
    marginTop: -8,
  },
  todoArrow: {
    width: 10,
    height: 10,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#8d826f",
    transform: [{ rotate: "45deg" }],
  },
  todoArrowUp: {
    transform: [{ rotate: "-135deg" }],
  },
  todoList: { gap: 7, paddingTop: 2 },
  todoRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  todoRowText: {
    flex: 1,
    color: "#3a352e",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
  todoRowTextDone: { color: "#a69d8e", textDecorationLine: "line-through" },
  todoRowTextCancelled: {
    color: "#b8afa0",
    textDecorationLine: "line-through",
  },
  todoStatusPending: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#d8cec0",
    backgroundColor: "#fffdf7",
    alignItems: "center",
    justifyContent: "center",
  },
  todoStatusCancelled: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#d8cec0",
    backgroundColor: "#eee8dc",
    alignItems: "center",
    justifyContent: "center",
  },
  todoStatusCompleted: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "#3a8f82",
    alignItems: "center",
    justifyContent: "center",
  },
  todoStatusCompletedText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  todoStatusRunningContainer: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  todoStatusRunningPulse1: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: "rgba(58,143,130,0.12)",
  },
  todoStatusRunningPulse2: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 999,
    backgroundColor: "rgba(58,143,130,0.24)",
  },
  todoStatusRunningCenter: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#3a8f82",
  },
  todoThinkingDots: { flexDirection: "row", alignItems: "center", gap: 3 },
  todoThinkingDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#999999",
  },
  todoThinkingDotOn: {
    backgroundColor: "#3a8f82",
    transform: [{ translateY: -0.5 }, { scale: 1.1 }],
  },
  todoThinkingDotMid: { backgroundColor: "#8d826f" },
  todoThinkingDotSoft: { backgroundColor: "#d8cec0" },
  contextCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    overflow: "visible",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 9,
  },
  contextPressable: { width: "100%" },
  contextHeadRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  contextHeadMain: { gap: 4, minWidth: 0 },
  contextInlineSummaryRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    minWidth: 0,
    alignSelf: "flex-start",
  },
  contextInlineTitle: {
    color: "#433b31",
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: FONT_UI_MEDIUM,
    flexShrink: 0,
  },
  contextBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
  },
  contextBadgeRunning: {
    backgroundColor: "#edf6f3",
    borderColor: "#c9e0d8",
  },
  contextBadgeDone: {
    backgroundColor: "#f5eee3",
    borderColor: "#e5d9c7",
  },
  contextBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONT_UI_MEDIUM,
  },
  contextBadgeTextRunning: { color: "#2f7f74" },
  contextBadgeTextDone: { color: "#7a6045" },
  contextTitle: { color: "#6a4126", fontSize: 12, fontWeight: "700" },
  contextSummary: { color: "#7f7467", fontSize: 12.5, lineHeight: 18, fontFamily: FONT_UI_REGULAR, flexShrink: 1 },
  contextDetail: { color: "#a18c76", fontSize: 11, lineHeight: 16, fontFamily: FONT_UI_REGULAR },
  contextTools: {
    gap: 9,
    marginTop: 6,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 2,
    backgroundColor: "transparent",
  },
  contextToolRow: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  contextToolRowSubtle: { paddingVertical: 2 },
  contextToolDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    marginTop: 6,
  },
  contextToolDotRunning: { backgroundColor: "#3a8f82" },
  contextToolDotCompleted: { backgroundColor: "#b69d7c" },
  contextToolDotError: { backgroundColor: "#b65b5b" },
  contextToolTitle: { color: "#6d4428", fontSize: 12, lineHeight: 18, fontFamily: FONT_UI_MEDIUM, minWidth: 0, flexShrink: 0 },
  contextToolDetail: { color: "#9a7a62", fontSize: 11, lineHeight: 17, flex: 1, fontFamily: FONT_UI_REGULAR },
  eventWrap: { width: "100%", alignItems: "flex-start", paddingVertical: 1 },
  eventCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    overflow: "visible",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 8,
  },
  eventHead: { flexDirection: "row", alignItems: "center", gap: 8 },
  eventDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#a8a29e",
  },
  eventDotRun: { backgroundColor: "#3a8f82" },
  eventTitle: { color: "#514a42", fontSize: 12.5, fontWeight: "600", fontFamily: FONT_MIXED_BODY_MEDIUM },
  eventMode: { color: "#8f8478", fontSize: 11, fontWeight: "500", fontFamily: FONT_MIXED_BODY_MEDIUM, flexShrink: 1 },
  eventTime: { marginLeft: "auto", color: "#a8a29e", fontSize: 10, fontFamily: FONT_MIXED_BODY_REGULAR },
  eventDetail: { color: "#7f7568", fontSize: 11, lineHeight: 17, fontFamily: FONT_MIXED_BODY_REGULAR, paddingLeft: 12 },
  eventMeta: { color: "#aa9c8b", fontSize: 10.5, lineHeight: 15, fontFamily: FONT_MIXED_BODY_REGULAR, paddingLeft: 12 },
  eventOutput: { color: "#57534e", fontSize: 11, lineHeight: 17, fontFamily: FONT_MIXED_BODY_REGULAR, paddingLeft: 12 },
  bashEventCard: {
    borderColor: "transparent",
    backgroundColor: "transparent",
  },
  bashEventDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#b08d5f",
  },
  bashEventDotRun: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d4a843",
  },
  bashEventTitle: { color: "#6b5b3e" },
  bashEventTime: { color: "#b0a08a" },
  bashEventDetail: { color: "#6b5b3e" },
  bashEventOutput: {
    color: "#57534e",
    backgroundColor: "#f7f3eb",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 11,
    lineHeight: 16,
    marginLeft: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eadfce",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  writeEventCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 8,
  },
  writeEventHead: { flexDirection: "row", alignItems: "center", gap: 6 },
  writeEventHeadMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  writeEventDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#b08d5f",
  },
  writeEventDotRun: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d4a843",
  },
  writeEventTitle: {
    flexShrink: 0,
    color: "#5e513f",
    fontSize: 12.5,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventDirectory: {
    color: "#93897b",
    fontSize: 11.5,
    lineHeight: 16,
    fontFamily: FONT_MIXED_BODY_REGULAR,
    flexShrink: 1,
    textAlign: "left",
  },
  writeEventTime: {
    marginLeft: "auto",
    color: "#b0a08a",
    fontSize: 10,
    lineHeight: 14,
    fontFamily: FONT_MIXED_BODY_REGULAR,
  },
  writeEventDetail: {
    color: "#807362",
    fontSize: 11,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
    paddingLeft: 12,
  },
  writeEventSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  writeEventAction: {
    color: "#7a5c3a",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "600",
    backgroundColor: "#f0e8d8",
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    overflow: "hidden",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventFile: {
    flexShrink: 1,
    color: "#4f4435",
    fontSize: 12.5,
    lineHeight: 17,
    fontWeight: "400",
    fontFamily: FONT_MIXED_BODY_REGULAR,
  },
  writeEventAdd: {
    color: "#1f8a5b",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventDel: {
    color: "#b65b5b",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventOutput: {
    color: "#57534e",
    fontSize: 11,
    lineHeight: 16,
    backgroundColor: "#f7f3eb",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontFamily: FONT_MIXED_BODY_REGULAR,
    marginLeft: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eadfce",
  },
  questionTimelineWrap: { width: "100%", alignItems: "flex-start" },
  questionTimelineCard: {
    width: "92%",
    maxWidth: "92%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e8ecf2",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  questionTimelineHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#f8f9fb",
    borderBottomWidth: 0,
    borderBottomColor: "#eef1f5",
  },
  questionTimelineTitleWrap: { flex: 1, minWidth: 0, gap: 2 },
  questionTimelineTitle: { color: "#1a2233", fontSize: 13, fontWeight: "700" },
  questionTimelineSummary: { color: "#697789", fontSize: 12, lineHeight: 16 },
  questionTimelineHeadRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 8,
  },
  questionTimelineBadge: {
    color: "#607287",
    fontSize: 10,
    backgroundColor: "#eef1f5",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 999,
    overflow: "hidden",
  },
  questionTimelineStatus: {
    color: "#8a95a6",
    fontSize: 11,
    backgroundColor: "#eef1f5",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  questionTimelineToggle: { color: "#5f6b7a", fontSize: 11, fontWeight: "700" },
  questionTimelineBody: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 5,
    borderTopWidth: 1,
    borderTopColor: "#eef1f5",
  },
  questionTimelineBlock: { gap: 5 },
  questionTimelineHeader: {
    color: "#5f6b7a",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 2,
  },
  questionTimelineText: {
    color: "#1a2233",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  questionTimelineHint: { color: "#9aa3b2", fontSize: 11, marginTop: 1 },
  questionTimelineOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e4e9f0",
    backgroundColor: "#f8f9fb",
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginVertical: 1,
  },
  questionTimelineOptionLive: {
    borderColor: "#0066b8",
    backgroundColor: "rgba(0, 102, 184, 0.06)",
  },
  questionTimelineRadio: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#c5cdd8",
    backgroundColor: "#fff",
  },
  questionTimelineCheckbox: {
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: "#c5cdd8",
    backgroundColor: "#fff",
  },
  questionTimelineOptionBody: { flex: 1 },
  questionTimelineOptionLabel: {
    color: "#1a2233",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 17,
  },
  questionTimelineOptionDesc: {
    color: "#7a8494",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
  },
  questionTimelineDisabled: { color: "#8a95a6", fontSize: 10, lineHeight: 14 },
  questionTimelineTabs: { flexDirection: "row", gap: 6, marginBottom: 5 },
  questionTimelineTab: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e4e9f0",
    backgroundColor: "#f8f9fb",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 7,
  },
  questionTimelineTabActive: {
    borderColor: "#2d3a4d",
    backgroundColor: "#2d3a4d",
  },
  questionTimelineTabText: {
    color: "#5f6b7a",
    fontSize: 11,
    fontWeight: "600",
  },
  questionTimelineTabTextActive: { color: "#ffffff" },
  errorCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#f0c9c9",
    backgroundColor: "#fff5f5",
    overflow: "hidden",
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 6,
  },
  errorTitle: { color: "#8e2f2f", fontSize: 13, fontWeight: "700" },
  errorCode: { color: "#b35656", fontSize: 11, fontWeight: "600" },
  thinkCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 20,
    borderWidth: 0,
    backgroundColor: "transparent",
    overflow: "hidden",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 0,
  },
  thinkCardExpanded: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 16,
    borderWidth: 0,
    backgroundColor: "#f3eee5",
    overflow: "hidden",
    paddingVertical: 11,
    paddingHorizontal: 12,
    gap: 8,
  },
  thinkHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  thinkIdentityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
    flex: 1,
  },
  thinkSpark: {
    color: "#3a8f82",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
  },
  thinkHeadMeta: { flexDirection: "row", alignItems: "center", gap: 8 },
  thinkTitle: {
    color: "#5d5345",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkToggleText: {
    color: "#8d826f",
    fontSize: 11,
    fontWeight: "700",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkExpandedHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  thinkExpandedTitle: {
    color: "#7c766c",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkText: {
    color: "#6f6657",
    fontSize: 13,
    lineHeight: 19,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkCollapsed: {
    color: "#7c766c",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkPreviewLines: { gap: 5, paddingTop: 2 },
  thinkPreviewLineRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  thinkPreviewDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#d8cec0",
  },
  thinkPreviewDotLive: {
    backgroundColor: "#3a8f82",
    transform: [{ scale: 1.25 }],
  },
  thinkPreviewLineText: {
    flex: 1,
    color: "#7c766c",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkFlowRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    paddingTop: 1,
  },
  thinkFlowIconShell: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24211d",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    shadowColor: "#503c1e",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  thinkFlowIconText: {
    color: "#ffffff",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  thinkFlowStatusDot: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#9aa6b2",
    borderWidth: 2,
    borderColor: "#f8f5ee",
  },
  thinkFlowStatusDotActive: { backgroundColor: "#3a8f82" },
  thinkFlowContent: { flex: 1, minWidth: 0, gap: 8 },
  thinkFlowDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginRight: 2,
  },
  thinkFlowDot: {
    width: 5.5,
    height: 5.5,
    borderRadius: 999,
    backgroundColor: "#5d5345",
  },
  thinkFlowDotActive: {
    backgroundColor: "#5d5345",
    opacity: 1,
    transform: [{ scale: 1.18 }],
  },
  thinkFlowDotMid: { backgroundColor: "#3a8f82", opacity: 0.75 },
  thinkFlowDotSoft: { backgroundColor: "#c9b99f", opacity: 0.58 },
  thinkFlowPill: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: "#fffdf7",
    borderWidth: 1,
    borderColor: "rgba(65,54,38,0.08)",
    paddingLeft: 14,
    paddingRight: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#503c1e",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  thinkFlowPillWaiting: {
    alignSelf: "flex-start",
    minWidth: 64,
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: "#fffdf7",
    borderWidth: 1,
    borderColor: "rgba(65,54,38,0.08)",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#503c1e",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  thinkFlowKicker: {
    color: "#3a8f82",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
    letterSpacing: 0.6,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkFlowLine: {
    flexShrink: 1,
    color: "#5d5345",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    letterSpacing: -0.1,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkFlowSteps: { gap: 6, paddingLeft: 8 },
  thinkFlowStepRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  thinkFlowStepDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d8cec0",
  },
  thinkFlowStepDotLive: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#3a8f82",
  },
  thinkFlowStepText: {
    flex: 1,
    color: "#8d826f",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  mdText: { fontSize: 15, lineHeight: 20, fontFamily: HANDWRITTEN_TEXT_FONT },
  mdInlineRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 0,
  },
  mdSegText: {
    fontSize: 15,
    lineHeight: 20,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  mdHeading: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    marginBottom: 4,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  mdInlineCode: { borderRadius: 4, paddingHorizontal: 4, fontSize: 13 },
  mdCodeBlock: { borderRadius: 8, backgroundColor: "#ece8df", padding: 8 },
  mdCodeText: { fontSize: 12, lineHeight: 18 },
  mdBulletRow: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  mdBulletDot: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkingWrap: { alignItems: "flex-start" },
  thinkingStickyWrap: { alignItems: "flex-start", paddingBottom: 6 },
  thinkingCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ddd4c5",
    backgroundColor: "#fffdf7",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  thinkingDots: { flexDirection: "row", alignItems: "center", gap: 4 },
  thinkingDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#c7d0de",
  },
  thinkingDotOn: { backgroundColor: "#6b7f98" },
  thinkingLabel: {
    color: "#667a94",
    fontSize: 12,
    fontWeight: "500",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  bubbleUserWrap: { width: "100%", alignItems: "flex-end", marginTop: 1 },
  bubbleAssistantWrap: { width: "100%", alignItems: "flex-start", marginTop: 1 },
  bubbleUser: {
    maxWidth: "84%",
    alignSelf: "flex-end",
    flexShrink: 1,
    borderRadius: 14,
    paddingVertical: 9,
    paddingHorizontal: 12,
    backgroundColor: "#1f2937",
    overflow: "hidden",
  },
  userAttachmentStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 6,
    marginBottom: 8,
  },
  userAttachmentImage: {
    width: 74,
    height: 74,
    borderRadius: 10,
    backgroundColor: "#334155",
  },
  // 探索中状态样式
  exploringStatusWrap: {
    width: "100%",
    alignItems: "flex-start",
    paddingTop: 2,
    paddingBottom: 0,
  },
  exploringThinkingText: {
    color: "#b6aea2",
    fontSize: 11,
    lineHeight: 14,
    fontFamily: FONT_UI_MEDIUM,
    letterSpacing: 0.1,
    minHeight: 14,
  },
  exploringStatusCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    paddingVertical: 3,
    paddingHorizontal: 2,
    gap: 5,
  },
  exploringStatusHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  exploringStatusTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  exploringStatusTitle: {
    color: "#4f463a",
    fontSize: 12.5,
    lineHeight: 16,
    fontFamily: FONT_UI_MEDIUM,
  },
  exploringStatusText: {
    color: "#5d5347",
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: FONT_UI_MEDIUM,
    flexShrink: 1,
  },
  exploringStatusMeta: {
    color: "#938778",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: FONT_UI_REGULAR,
  },
  exploringStatusListCard: {
    width: "96%",
    marginTop: 4,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 2,
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    gap: 7,
  },
  eventDiffList: {
    gap: 10,
    marginTop: 4,
    paddingLeft: 12,
  },
  eventDiffBlock: {
    gap: 8,
    paddingLeft: 12,
  },
  eventDiffHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  eventDiffPath: {
    flex: 1,
    color: "#6b5b3e",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: FONT_UI_REGULAR,
  },
  eventDiffCodeWindow: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#eadfce",
    backgroundColor: "#faf7f1",
    overflow: "hidden",
  },
  eventDiffCodeWrap: {
    maxHeight: 280,
  },
  eventDiffCodeCanvas: {
    minWidth: "100%",
    paddingVertical: 6,
  },
  eventDiffRow: {
    minHeight: 20,
    paddingHorizontal: 8,
    paddingVertical: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  eventDiffRowContext: {
    backgroundColor: "transparent",
  },
  eventDiffRowAdd: {
    backgroundColor: "rgba(31,138,91,0.10)",
  },
  eventDiffRowDelete: {
    backgroundColor: "rgba(182,91,91,0.10)",
  },
  eventDiffRowHunk: {
    backgroundColor: "#f2ede5",
  },
  eventDiffRowNote: {
    backgroundColor: "#efe9df",
  },
  eventDiffLineNumber: {
    width: 28,
    textAlign: "right",
    color: "#b2a591",
    fontSize: 10,
    lineHeight: 16,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  eventDiffLineNumberMuted: {
    color: "transparent",
  },
  eventDiffMarker: {
    width: 10,
    color: "#9d907f",
    fontSize: 10,
    lineHeight: 16,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  eventDiffCodeText: {
    color: "#4b453d",
    fontSize: 11,
    lineHeight: 16,
    flexShrink: 0,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  disclosureChevron: {
    width: 11,
    height: 11,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transform: [{ rotate: "-90deg" }],
  },
  disclosureChevronExpanded: {
    transform: [{ rotate: "0deg" }],
  },
  disclosureChevronLineLeft: {
    position: "absolute",
    width: 4.5,
    height: 1,
    borderRadius: 999,
    backgroundColor: "#c4b7a5",
    transform: [{ translateX: -1.2 }, { rotate: "45deg" }],
  },
  disclosureChevronLineRight: {
    position: "absolute",
    width: 4.5,
    height: 1,
    borderRadius: 999,
    backgroundColor: "#c4b7a5",
    transform: [{ translateX: 1.2 }, { rotate: "-45deg" }],
  },
} satisfies MobileNamedStyles;
