import {
  FONT_DISPLAY_SERIF,
  FONT_TEXT_SERIF,
  FONT_UI_MEDIUM,
  FONT_UI_REGULAR,
} from "./mobileFonts";
import type { MobileNamedStyles } from "./mobileStyleTypes";

export const authStyles = {
  authScroll: { flex: 1 },
  authContainer: { padding: 20, gap: 12, paddingBottom: 28 },
  authContainerCenter: {
    flexGrow: 1,
    width: "100%",
    minHeight: "100%",
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  authPageFrame: {
    flex: 1,
    minHeight: 520,
    width: "100%",
    paddingHorizontal: 22,
    paddingVertical: 36,
    justifyContent: "center",
  },
  authHeroPanel: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    position: "relative",
  },
  authHeroOrb: {
    position: "absolute",
    width: 240,
    height: 240,
    borderRadius: 999,
    right: -94,
    top: -116,
    backgroundColor: "rgba(58,143,130,0.08)",
  },
  brandRow: { flexDirection: "row", alignItems: "center" },
  authKicker: {
    color: "#8d826f",
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: FONT_UI_MEDIUM,
  },
  authTitle: {
    fontSize: 34,
    lineHeight: 38,
    color: "#24211d",
    letterSpacing: -1.2,
    fontFamily: FONT_DISPLAY_SERIF,
  },
  authSub: {
    color: "#655d52",
    fontSize: 17,
    lineHeight: 25,
    marginBottom: 2,
    fontFamily: FONT_TEXT_SERIF,
  },
  authHeroCopy: {
    gap: 6,
    marginBottom: 18,
    paddingHorizontal: 6,
  },
  authFormWrap: {
    width: "100%",
    gap: 14,
  },
  authCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(93,83,69,0.12)",
    backgroundColor: "#fffdf7",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    gap: 12,
    shadowColor: "#5d5345",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  authFieldGroup: { gap: 6 },
  authFieldLabel: {
    color: "#8d826f",
    fontSize: 11,
    paddingLeft: 2,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    fontFamily: FONT_UI_MEDIUM,
  },
  authSchemeRow: { flexDirection: "row", gap: 8, marginBottom: 2 },
  authSchemeChip: {
    paddingHorizontal: 10,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d8e1ec",
    backgroundColor: "#f7fafd",
    alignItems: "center",
    justifyContent: "center",
  },
  authSchemeChipActive: {
    paddingHorizontal: 10,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#1f2937",
    backgroundColor: "#1f2937",
    alignItems: "center",
    justifyContent: "center",
  },
  authSchemeChipText: { color: "#5f7087", fontSize: 12, fontWeight: "700" },
  authSchemeChipTextActive: {
    color: "#f9fbff",
    fontSize: 12,
    fontWeight: "700",
  },
  authInput: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ddd4c5",
    backgroundColor: "#fbf7ef",
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#2f3948",
    fontFamily: FONT_UI_REGULAR,
  },
  authUrlRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ddd4c5",
    backgroundColor: "#fbf7ef",
    paddingLeft: 14,
    paddingRight: 8,
    gap: 8,
  },
  authInputUrl: {
    flex: 1,
    minHeight: 50,
    backgroundColor: "transparent",
    paddingHorizontal: 0,
    paddingVertical: 10,
    color: "#2f3948",
    fontFamily: FONT_UI_REGULAR,
  },
  authScanInlineBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d8d0c2",
    backgroundColor: "#f3ede2",
    alignItems: "center",
    justifyContent: "center",
  },
  authScanInlineTxt: { color: "#3f5167", fontSize: 12, fontWeight: "700" },
  authScanIconFrame: {
    width: 16,
    height: 16,
    position: "relative",
  },
  authScanIconLt: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 6,
    height: 6,
    borderLeftWidth: 1.8,
    borderTopWidth: 1.8,
    borderColor: "#5d5345",
  },
  authScanIconRt: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 6,
    height: 6,
    borderRightWidth: 1.8,
    borderTopWidth: 1.8,
    borderColor: "#5d5345",
  },
  authScanIconLb: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: 6,
    height: 6,
    borderLeftWidth: 1.8,
    borderBottomWidth: 1.8,
    borderColor: "#5d5345",
  },
  authScanIconRb: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 6,
    height: 6,
    borderRightWidth: 1.8,
    borderBottomWidth: 1.8,
    borderColor: "#5d5345",
  },
  authTinyRow: {
    marginTop: 7,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  authTinyRowBottom: {
    marginTop: 18,
    marginBottom: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  authAssistRow: {
    marginTop: 2,
    gap: 12,
  },
  authTinyCheckWrap: { flexDirection: "row", alignItems: "center", gap: 6 },
  authTinyCheckOn: {
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "#5d5345",
    backgroundColor: "#5d5345",
  },
  authTinyCheckOff: {
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "#b9ae9c",
    backgroundColor: "#fffdf7",
  },
  authTinyText: { color: "#6f6657", fontSize: 12, fontFamily: FONT_UI_REGULAR },
  authPillRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  authSecondaryPill: {
    height: 36,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#ddd4c5",
    backgroundColor: "#f7f1e6",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  authSecondaryPillText: {
    color: "#5d5345",
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONT_UI_MEDIUM,
    includeFontPadding: false,
  },
  authTinyLinkBtn: { paddingVertical: 2, paddingHorizontal: 2 },
  authTinyLinkText: {
    color: "#4f6f98",
    fontSize: 11,
    textDecorationLine: "underline",
  },
  authQuickRow: { flexDirection: "row", gap: 8, marginTop: 6 },
  authQuickBtn: {
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d2dde9",
    backgroundColor: "#f6f9fd",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authQuickBtnText: { color: "#41546c", fontSize: 12, fontWeight: "700" },
  authActionRow: { flexDirection: "row", gap: 8, marginTop: 4 },
  authConnectBtn: {
    flex: 1,
    minHeight: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#24211d",
  },
  authConnectBtnText: {
    color: "#fffdf7",
    fontSize: 15,
    lineHeight: 20,
    fontFamily: FONT_UI_MEDIUM,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  authNoticeRow: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e6dfd2",
    backgroundColor: "#f6f1e8",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  authNoticeText: {
    color: "#6f6657",
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
    fontFamily: FONT_TEXT_SERIF,
  },
  authFootHint: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#eee6d8",
    backgroundColor: "#fcf8f0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  authFootHintText: {
    flex: 1,
    color: "#857a69",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: FONT_TEXT_SERIF,
  },
  authPane: { gap: 10 },
  authModeList: { gap: 10 },
  authModeCard: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: "#dde5ef",
    backgroundColor: "#ffffff",
    gap: 4,
  },
  authModeTitle: { color: "#2b3442", fontSize: 15, fontWeight: "700" },
  authModeDesc: { color: "#6d7b8f", fontSize: 12, lineHeight: 18 },
  authModeBackBtn: {
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d9e1ec",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f7fafc",
  },
  authModeBackTxt: { color: "#4f5f74", fontWeight: "600", fontSize: 12 },
  scanHeroBtn: {
    height: 52,
    borderRadius: 14,
    backgroundColor: "#1f2937",
    alignItems: "center",
    justifyContent: "center",
  },
  scanHeroBtnText: { color: "#f9fafb", fontWeight: "700", fontSize: 16 },
  authHintBox: {
    borderRadius: 14,
    padding: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e6e8ec",
    gap: 4,
  },
  authHint: { color: "#5f6a7a" },
  fallbackCard: {
    borderRadius: 14,
    padding: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e6e8ec",
    gap: 8,
  },
  fallbackTitle: { color: "#303744", fontWeight: "600" },
  fallbackInput: {
    minHeight: 92,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dfe3e8",
    backgroundColor: "#f9fafb",
    padding: 10,
    color: "#263041",
    textAlignVertical: "top",
  },
  fallbackBtn: {
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1f2937",
  },
  fallbackBtnText: { color: "#fff", fontWeight: "600" },
  authStatusMini: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e3e8ef",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  authStatusMiniText: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
  },
  authStatusBox: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e0e5eb",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  authStatusText: { color: "#5f6b7c", flex: 1 },

  scannerWrap: { flex: 1, padding: 14, gap: 10 },
  scannerHintText: { color: "#5a6a80", fontSize: 13 },
  scannerFrame: {
    flex: 1,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#dde3ea",
    backgroundColor: "#fff",
  },
} satisfies MobileNamedStyles;
