import { Platform, StyleSheet } from "react-native";
import {
  FONT_DISPLAY_SERIF,
  FONT_MIXED_BODY_MEDIUM,
  FONT_MIXED_BODY_REGULAR,
  FONT_TEXT_SERIF,
  FONT_TEXT_SERIF_SEMIBOLD,
  FONT_UI_MEDIUM,
  FONT_UI_REGULAR,
  HANDWRITTEN_TEXT_FONT,
} from "./mobileFonts";
import type { MobileNamedStyles } from "./mobileStyleTypes";

export const chatStyles = {
  topBar: {
    height: 52,
    paddingHorizontal: 10,
    paddingTop: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    position: "relative",
    overflow: "visible",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  notebookShell: {
    flex: 1,
    backgroundColor: "#1A1A1A",
    position: "relative",
  },
  notebookTrack: {
    flex: 1,
    flexDirection: "row",
  },
  notebookPageFrame: {
    flex: 1,
  },
  notebookMainPage: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#1e1e1e",
  },
  slideDrawerSurface: {
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: "#3c3c3c",
  },
  slideDrawerSurfaceRight: {
    borderRightWidth: 0,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "#3c3c3c",
  },
  slideDrawerContent: {
    flex: 1,
    height: "100%",
    backgroundColor: "transparent",
  },
  slideDrawerOverlay: {
    backgroundColor: "rgba(36,33,29,0.22)",
  },
  chatStageViewport: {
    flex: 1,
    minHeight: 0,
  },
  keyboardAwareContent: {
    flex: 1,
    minHeight: 0,
  },
  streamTopGlowTrack: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(58, 143, 130, 0.10)",
    overflow: "hidden",
    zIndex: 8,
    elevation: 8,
  },
  streamTopGlowSweep: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 220,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(58, 143, 130, 0.62)",
  },
  topSideSlot: { alignItems: "center", justifyContent: "center", zIndex: 25 },
  topSideSlotRight: { alignItems: "center", justifyContent: "center", zIndex: 25 },
  topNavButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.05)",
    position: "relative",
  },
  topNavGlyph: {
    opacity: 0.95,
  },
  topNavGlyphActive: {
    opacity: 1,
  },
  topBrand: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    zIndex: 1,
  },
  topTitle: {
    fontSize: 20,
    color: "#1A1A1F",
    fontWeight: "700",
    fontFamily: FONT_UI_MEDIUM,
  },
  topTitleCompact: {
    fontSize: 16,
    lineHeight: 20,
    color: "#1A1A1F",
    fontWeight: "600",
    fontFamily: FONT_UI_MEDIUM,
  },
  topWorkspaceText: {
    fontSize: 11,
    lineHeight: 14,
    color: "#6E6E7A",
    fontWeight: "500",
  },
  toolBtn: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "#222325",
  },
  toolBtnImage: { width: 16, height: 16 },
  chatStatusBar: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 6,
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
  },
  chatStatusText: {
    color: "#9da5b4",
    fontSize: 12,
    lineHeight: 17,
    flex: 1,
  },
  chatStatusCopyBtn: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d2d2d",
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "#1e1e1e",
  },
  chatStatusCopyTxt: { color: "#536278", fontSize: 11, fontWeight: "600" },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "#222325",
  },
  iconTxt: { color: "#394455", fontWeight: "700" },

  chatBodyWrap: { flex: 1, paddingHorizontal: 16, position: "relative" },
  chatListStage: { flex: 1, position: "relative" },
  sessionSwitchOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 24,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 14,
    backgroundColor: "rgba(248, 246, 241, 0.92)",
  },
  blankWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 28,
    paddingBottom: 24,
  },
  blankHero: {
    alignSelf: "center",
    alignItems: "center",
    width: "100%",
    maxWidth: 340,
    gap: 12,
  },
  blankTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: "#1A1A1F",
    fontFamily: FONT_UI_MEDIUM,
    fontWeight: "600",
    letterSpacing: -0.4,
    textAlign: "center",
  },
  blankTitleWorkspace: {
    color: "#1A1A1F",
    letterSpacing: -0.2,
    fontWeight: "700",
  },
  blankSub: {
    color: "#6E6E7A",
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONT_UI_REGULAR,
    textAlign: "center",
    maxWidth: 300,
  },
  blankActionBtn: {
    marginTop: 8,
    minHeight: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  blankActionText: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: FONT_UI_MEDIUM,
  },
  sessionSwitchWrap: {
    justifyContent: "center",
  },
  sessionSwitchHero: {
    gap: 14,
  },
  sessionSwitchTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontFamily: FONT_TEXT_SERIF_SEMIBOLD,
    letterSpacing: -0.3,
  },
  sessionSwitchRail: {
    height: 4,
    borderRadius: 999,
    borderWidth: 1,
    overflow: "hidden",
    marginTop: 2,
  },
  sessionSwitchRailFill: {
    width: "38%",
    height: "100%",
    borderRadius: 999,
    opacity: 0.82,
  },

  turnWrap: { width: "100%", alignSelf: "stretch", gap: 8 },
  historyOverlay: {
    position: "absolute",
    top: 6,
    left: 0,
    right: 0,
    alignItems: "center",
    gap: 6,
  },
  historyOverlayRail: {
    width: "46%",
    maxWidth: 176,
    height: 2,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "#3c3c3c",
  },
  historyOverlayFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(86,77,63,0.58)",
  },
  historyOverlayFillActive: {
    width: "100%",
  },
  historyOverlayHint: {
    color: "#8b6c45",
    fontSize: 11,
    lineHeight: 14,
    fontFamily: FONT_UI_MEDIUM,
    backgroundColor: "rgba(255,253,247,0.82)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  historyHintWrap: { alignItems: "center", paddingTop: 4, paddingBottom: 2 },
  historyHintText: { color: "#7c8aa0", fontSize: 12 },
  thinkWrap: { width: "100%", alignItems: "flex-start" },
  contextWrap: { width: "100%", alignItems: "flex-start", paddingVertical: 1 },
  todoInlineWrap: { width: "100%", alignItems: "flex-start" },
  dividerWrap: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 2,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: "#3c3c3c" },
  dividerLabel: { color: "#9da5b4", fontSize: 11 },
  errorWrap: { width: "100%", alignItems: "flex-start" },
  todoInlineCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
    paddingVertical: 12,
    paddingHorizontal: 13,
    gap: 12,
    shadowColor: "#d4d4d4",
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 1,
  },
  todoInlineCardCompact: {
    width: "100%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
    paddingVertical: 12,
    paddingHorizontal: 13,
    gap: 12,
  },
  todoCardHead: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  todoCardHeadCompact: { flexDirection: "row", alignItems: "center", gap: 10 },
  todoCardHeadMain: { flex: 1, gap: 7 },
  todoTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  todoTitle: {
    color: "#d4d4d4",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  todoActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 4,
  },
  todoChipRunning: {
    minWidth: 42,
    height: 21,
    borderRadius: 999,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2d2d2d",
    borderWidth: 1,
    borderColor: "#3c3c3c",
  },
  todoChipRunningText: { color: "#10A37F", fontSize: 11, fontWeight: "800" },
  todoChipDone: {
    minWidth: 42,
    height: 21,
    borderRadius: 999,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2d2d2d",
    borderWidth: 1,
    borderColor: "#3c3c3c",
  },
  todoChipDoneText: { color: "#9da5b4", fontSize: 11, fontWeight: "800" },
  todoSummary: {
    color: "#9da5b4",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  todoProgressTrack: {
    height: 5,
    borderRadius: 999,
    backgroundColor: "#e5ded2",
    overflow: "hidden",
  },
  todoProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#10A37F",
  },
  todoChevron: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "0deg" }],
  },
  todoChevronCollapsed: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-90deg" }],
  },
  todoChevronLineLeft: {
    position: "absolute",
    width: 6,
    height: 1.5,
    borderRadius: 999,
    backgroundColor: "#9da5b4",
    transform: [{ translateX: -1.5 }, { rotate: "45deg" }],
  },
  todoChevronLineRight: {
    position: "absolute",
    width: 6,
    height: 1.5,
    borderRadius: 999,
    backgroundColor: "#9da5b4",
    transform: [{ translateX: 1.5 }, { rotate: "-45deg" }],
  },
  todoCloseBtn: {
    width: 22,
    height: 22,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2d2d2d",
    marginLeft: 4,
  },
  todoCloseText: {
    color: "#9da5b4",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: -1,
  },
  todoToggleBtn: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
    marginTop: -8,
  },
  todoArrow: {
    width: 10,
    height: 10,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#9da5b4",
    transform: [{ rotate: "45deg" }],
  },
  todoArrowUp: {
    transform: [{ rotate: "-135deg" }],
  },
  todoList: { gap: 7, paddingTop: 2 },
  todoRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  todoRowText: {
    flex: 1,
    color: "#d4d4d4",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
  todoRowTextDone: { color: "#9da5b4", textDecorationLine: "line-through" },
  todoRowTextCancelled: {
    color: "#b8afa0",
    textDecorationLine: "line-through",
  },
  todoStatusPending: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
    alignItems: "center",
    justifyContent: "center",
  },
  todoStatusCancelled: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#3c3c3c",
    backgroundColor: "#2d2d2d",
    alignItems: "center",
    justifyContent: "center",
  },
  todoStatusCompleted: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "#10A37F",
    alignItems: "center",
    justifyContent: "center",
  },
  todoStatusCompletedText: {
    color: "#252526",
    fontSize: 12,
    fontWeight: "700",
  },
  todoStatusRunningContainer: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  todoStatusRunningPulse1: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: "rgba(58,143,130,0.12)",
  },
  todoStatusRunningPulse2: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 999,
    backgroundColor: "rgba(58,143,130,0.24)",
  },
  todoStatusRunningCenter: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#10A37F",
  },
  todoThinkingDots: { flexDirection: "row", alignItems: "center", gap: 3 },
  todoThinkingDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#999999",
  },
  todoThinkingDotOn: {
    backgroundColor: "#10A37F",
    transform: [{ translateY: -0.5 }, { scale: 1.1 }],
  },
  todoThinkingDotMid: { backgroundColor: "#9da5b4" },
  todoThinkingDotSoft: { backgroundColor: "#3c3c3c" },
  contextCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    overflow: "visible",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 9,
  },
  toolBatchWrap: {
    width: "96%",
    maxWidth: "96%",
    paddingVertical: 2,
    paddingHorizontal: 2,
    gap: 4,
  },
  toolBatchHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  toolBatchLabel: {
    color: "#A3A3A3",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
    fontFamily: FONT_UI_MEDIUM,
  },
  toolBatchLabelActive: {
    color: "#39FF14",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
    fontFamily: FONT_UI_MEDIUM,
  },
  toolBatchCount: {
    flex: 1,
    color: "#A3A3A3",
    fontSize: 11,
    lineHeight: 15,
    fontFamily: FONT_UI_REGULAR,
  },
  toolBatchList: {
    paddingLeft: 12,
    gap: 2,
    paddingBottom: 4,
  },
  contextPressable: { width: "100%" },
  contextHeadRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  contextHeadMain: { gap: 4, minWidth: 0 },
  contextInlineSummaryRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    minWidth: 0,
    alignSelf: "flex-start",
  },
  contextInlineTitle: {
    color: "#433b31",
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: FONT_UI_MEDIUM,
    flexShrink: 0,
  },
  contextBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
  },
  contextBadgeRunning: {
    backgroundColor: "#2d2d2d",
    borderColor: "#c9e0d8",
  },
  contextBadgeDone: {
    backgroundColor: "#2d2d2d",
    borderColor: "#e5d9c7",
  },
  contextBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONT_UI_MEDIUM,
  },
  contextBadgeTextRunning: { color: "#10A37F" },
  contextBadgeTextDone: { color: "#7a6045" },
  contextTitle: { color: "#6a4126", fontSize: 12, fontWeight: "700" },
  contextSummary: { color: "#7f7467", fontSize: 12.5, lineHeight: 18, fontFamily: FONT_UI_REGULAR, flexShrink: 1 },
  contextDetail: { color: "#a18c76", fontSize: 11, lineHeight: 16, fontFamily: FONT_UI_REGULAR },
  contextTools: {
    gap: 9,
    marginTop: 6,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 2,
    backgroundColor: "transparent",
  },
  contextToolRow: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  contextToolRowSubtle: { paddingVertical: 2 },
  contextToolDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    marginTop: 6,
  },
  contextToolDotRunning: { backgroundColor: "#10A37F" },
  contextToolDotCompleted: { backgroundColor: "#b69d7c" },
  contextToolDotError: { backgroundColor: "#cf6679" },
  contextToolTitle: { color: "#6d4428", fontSize: 12, lineHeight: 18, fontFamily: FONT_UI_MEDIUM, minWidth: 0, flexShrink: 0 },
  contextToolDetail: { color: "#9a7a62", fontSize: 11, lineHeight: 17, flex: 1, fontFamily: FONT_UI_REGULAR },
  eventWrap: { width: "100%", alignItems: "flex-start", paddingVertical: 1 },
  eventExpandBody: {
    width: "100%",
    gap: 6,
    paddingTop: 2,
    paddingBottom: 4,
  },
  eventCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    overflow: "visible",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 8,
  },
  eventHead: { flexDirection: "row", alignItems: "center", gap: 8 },
  eventDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#9da5b4",
  },
  eventDotRun: { backgroundColor: "#10A37F" },
  eventTitle: { color: "#514a42", fontSize: 12.5, fontWeight: "600", fontFamily: FONT_MIXED_BODY_MEDIUM },
  eventMode: { color: "#8f8478", fontSize: 11, fontWeight: "500", fontFamily: FONT_MIXED_BODY_MEDIUM, flexShrink: 1 },
  eventTime: { marginLeft: "auto", color: "#9da5b4", fontSize: 10, fontFamily: FONT_MIXED_BODY_REGULAR },
  eventDetail: { color: "#7f7568", fontSize: 11, lineHeight: 17, fontFamily: FONT_MIXED_BODY_REGULAR, paddingLeft: 12 },
  eventMeta: { color: "#aa9c8b", fontSize: 10.5, lineHeight: 15, fontFamily: FONT_MIXED_BODY_REGULAR, paddingLeft: 12 },
  eventOutput: { color: "#9da5b4", fontSize: 11, lineHeight: 17, fontFamily: FONT_MIXED_BODY_REGULAR, paddingLeft: 12 },
  bashTerminalWrap: {
    width: "96%",
    maxWidth: "96%",
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  bashTerminalCard: {
    borderRadius: 12,
    backgroundColor: "#1A1A1F",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  bashTerminalCardRun: {
    borderColor: "rgba(16,163,127,0.45)",
  },
  bashTerminalCardError: {
    borderColor: "rgba(227,72,79,0.45)",
    backgroundColor: "#221A1B",
  },
  bashTerminalCommand: {
    color: "#E8E8ED",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  bashTerminalDollar: {
    color: "#10A37F",
    fontWeight: "600",
  },
  bashTerminalOutput: {
    color: "#A8A8B3",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  bashTerminalOutputError: {
    color: "#F0A0A4",
  },
  // 旧 bash 样式保留键名以免别处引用，实际已改走 bashTerminal*
  bashEventCard: {
    borderColor: "transparent",
    backgroundColor: "transparent",
  },
  bashEventDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#10A37F",
  },
  bashEventDotRun: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d29922",
  },
  bashEventTitle: { color: "#10A37F" },
  bashEventTime: { color: "#9da5b4" },
  bashEventDetail: { color: "#10A37F" },
  bashEventOutput: {
    color: "#9da5b4",
    backgroundColor: "#1e1e1e",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 11,
    lineHeight: 16,
    marginLeft: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2d2d2d",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  writeEventCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 8,
  },
  writeEventHead: { flexDirection: "row", alignItems: "center", gap: 6 },
  writeEventHeadMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  writeEventDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#10A37F",
  },
  writeEventDotRun: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d29922",
  },
  writeEventTitle: {
    flexShrink: 0,
    color: "#5e513f",
    fontSize: 12.5,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventDirectory: {
    color: "#93897b",
    fontSize: 11.5,
    lineHeight: 16,
    fontFamily: FONT_MIXED_BODY_REGULAR,
    flexShrink: 1,
    textAlign: "left",
  },
  writeEventTime: {
    marginLeft: "auto",
    color: "#9da5b4",
    fontSize: 10,
    lineHeight: 14,
    fontFamily: FONT_MIXED_BODY_REGULAR,
  },
  writeEventDetail: {
    color: "#807362",
    fontSize: 11,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
    paddingLeft: 12,
  },
  writeEventSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  writeEventAction: {
    color: "#7a5c3a",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "600",
    backgroundColor: "#2d2d2d",
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    overflow: "hidden",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventFile: {
    flexShrink: 1,
    color: "#4f4435",
    fontSize: 12.5,
    lineHeight: 17,
    fontWeight: "400",
    fontFamily: FONT_MIXED_BODY_REGULAR,
  },
  writeEventAdd: {
    color: "#1f8a5b",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventDel: {
    color: "#cf6679",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: FONT_MIXED_BODY_MEDIUM,
  },
  writeEventOutput: {
    color: "#9da5b4",
    fontSize: 11,
    lineHeight: 16,
    backgroundColor: "#1e1e1e",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontFamily: FONT_MIXED_BODY_REGULAR,
    marginLeft: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2d2d2d",
  },
  questionTimelineWrap: { width: "100%", alignItems: "flex-start" },
  questionTimelineCard: {
    width: "92%",
    maxWidth: "92%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2d2d2d",
    backgroundColor: "#252526",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#d4d4d4",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  questionTimelineHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#1e1e1e",
    borderBottomWidth: 0,
    borderBottomColor: "#222325",
  },
  questionTimelineTitleWrap: { flex: 1, minWidth: 0, gap: 2 },
  questionTimelineTitle: { color: "#d4d4d4", fontSize: 13, fontWeight: "700" },
  questionTimelineSummary: { color: "#697789", fontSize: 12, lineHeight: 16 },
  questionTimelineHeadRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 8,
  },
  questionTimelineBadge: {
    color: "#607287",
    fontSize: 10,
    backgroundColor: "#222325",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 999,
    overflow: "hidden",
  },
  questionTimelineStatus: {
    color: "#9da5b4",
    fontSize: 11,
    backgroundColor: "#222325",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  questionTimelineToggle: { color: "#9da5b4", fontSize: 11, fontWeight: "700" },
  questionTimelineBody: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 5,
    borderTopWidth: 1,
    borderTopColor: "#222325",
  },
  questionTimelineBlock: { gap: 5 },
  questionTimelineHeader: {
    color: "#9da5b4",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 2,
  },
  questionTimelineText: {
    color: "#d4d4d4",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  questionTimelineHint: { color: "#9aa3b2", fontSize: 11, marginTop: 1 },
  questionTimelineOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d2d2d",
    backgroundColor: "#1e1e1e",
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginVertical: 1,
  },
  questionTimelineOptionLive: {
    borderColor: "#0066b8",
    backgroundColor: "rgba(0, 102, 184, 0.06)",
  },
  questionTimelineRadio: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
  },
  questionTimelineCheckbox: {
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
  },
  questionTimelineOptionBody: { flex: 1 },
  questionTimelineOptionLabel: {
    color: "#d4d4d4",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 17,
  },
  questionTimelineOptionDesc: {
    color: "#7a8494",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
  },
  questionTimelineDisabled: { color: "#9da5b4", fontSize: 10, lineHeight: 14 },
  questionTimelineTabs: { flexDirection: "row", gap: 6, marginBottom: 5 },
  questionTimelineTab: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2d2d2d",
    backgroundColor: "#1e1e1e",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 7,
  },
  questionTimelineTabActive: {
    borderColor: "#2d3a4d",
    backgroundColor: "#2d3a4d",
  },
  questionTimelineTabText: {
    color: "#9da5b4",
    fontSize: 11,
    fontWeight: "600",
  },
  questionTimelineTabTextActive: { color: "#252526" },
  errorCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a1d25",
    backgroundColor: "#2d2224",
    overflow: "hidden",
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 6,
  },
  errorTitle: { color: "#8e2f2f", fontSize: 13, fontWeight: "700" },
  errorCode: { color: "#b35656", fontSize: 11, fontWeight: "600" },
  thinkCard: {
    width: "100%",
    maxWidth: "100%",
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    overflow: "hidden",
    paddingVertical: 2,
    paddingHorizontal: 0,
    gap: 0,
  },
  thinkCardExpanded: {
    width: "100%",
    maxWidth: "100%",
    borderRadius: 14,
    borderWidth: 0,
    backgroundColor: "#F7F7F8",
    overflow: "hidden",
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 6,
  },
  thinkHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  thinkIdentityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
    flex: 1,
  },
  thinkSpark: {
    color: "#10A37F",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
  },
  thinkHeadMeta: { flexDirection: "row", alignItems: "center", gap: 8 },
  thinkTitle: {
    color: "#9da5b4",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkToggleText: {
    color: "#6E6E7A",
    fontSize: 12,
    fontWeight: "500",
    fontFamily: FONT_UI_REGULAR,
  },
  thinkExpandedHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  thinkExpandBody: {
    width: "100%",
    paddingTop: 2,
    paddingBottom: 6,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  thinkExpandedTitle: {
    color: "#6E6E7A",
    fontSize: 12.5,
    fontWeight: "600",
    fontFamily: FONT_UI_MEDIUM,
  },
  thinkText: {
    color: "#6E6E7A",
    fontSize: 13,
    lineHeight: 19,
    fontFamily: FONT_UI_REGULAR,
  },
  thinkCollapsed: {
    color: "#6E6E7A",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: FONT_UI_REGULAR,
  },
  thinkPreviewLines: { gap: 5, paddingTop: 2 },
  thinkPreviewLineRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  thinkPreviewDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#3c3c3c",
  },
  thinkPreviewDotLive: {
    backgroundColor: "#10A37F",
    transform: [{ scale: 1.25 }],
  },
  thinkPreviewLineText: {
    flex: 1,
    color: "#9da5b4",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkFlowRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    paddingTop: 1,
  },
  thinkFlowStatusDot: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#9aa6b2",
    borderWidth: 2,
    borderColor: "#1e1e1e",
  },
  thinkFlowStatusDotActive: { backgroundColor: "#10A37F" },
  thinkFlowContent: { flex: 1, minWidth: 0, gap: 8 },
  thinkFlowDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginRight: 2,
  },
  thinkFlowDot: {
    width: 5.5,
    height: 5.5,
    borderRadius: 999,
    backgroundColor: "#9da5b4",
  },
  thinkFlowDotActive: {
    backgroundColor: "#9da5b4",
    opacity: 1,
    transform: [{ scale: 1.18 }],
  },
  thinkFlowDotMid: { backgroundColor: "#10A37F", opacity: 0.75 },
  thinkFlowDotSoft: { backgroundColor: "#9da5b4", opacity: 0.58 },
  thinkFlowPill: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    minHeight: 28,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    paddingLeft: 0,
    paddingRight: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    justifyContent: "flex-start",
    overflow: "visible",
    shadowOpacity: 0,
    elevation: 0,
  },
  thinkFlowPillWaiting: {
    alignSelf: "flex-start",
    minWidth: 0,
    minHeight: 28,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    paddingHorizontal: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    overflow: "visible",
    shadowOpacity: 0,
    elevation: 0,
  },
  thinkFlowKicker: {
    color: "#6E6E7A",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
    fontFamily: FONT_UI_MEDIUM,
  },
  thinkFlowLine: {
    flexShrink: 1,
    color: "#6E6E7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    letterSpacing: -0.1,
    fontFamily: FONT_UI_MEDIUM,
  },
  thinkFlowChevron: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "400",
    marginLeft: 2,
  },
  thinkFlowSteps: { gap: 6, paddingLeft: 8 },
  thinkFlowStepRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  thinkFlowStepDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#3c3c3c",
  },
  thinkFlowStepDotLive: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#10A37F",
  },
  thinkFlowStepText: {
    flex: 1,
    color: "#9da5b4",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  mdText: { fontSize: 15, lineHeight: 20, fontFamily: HANDWRITTEN_TEXT_FONT },
  mdInlineRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 0,
  },
  mdSegText: {
    fontSize: 15,
    lineHeight: 20,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  mdHeading: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    marginBottom: 4,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  mdInlineCode: { borderRadius: 4, paddingHorizontal: 4, fontSize: 13 },
  mdCodeBlock: { borderRadius: 8, backgroundColor: "#2d2d2d", padding: 8 },
  mdCodeText: { fontSize: 12, lineHeight: 18 },
  mdBulletRow: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  mdBulletDot: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  thinkingWrap: { alignItems: "flex-start" },
  thinkingStickyWrap: { alignItems: "flex-start", paddingBottom: 6 },
  thinkingCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3c3c3c",
    backgroundColor: "#252526",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  thinkingDots: { flexDirection: "row", alignItems: "center", gap: 4 },
  thinkingDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#c7d0de",
  },
  thinkingDotOn: { backgroundColor: "#6b7f98" },
  thinkingLabel: {
    color: "#667a94",
    fontSize: 12,
    fontWeight: "500",
    fontFamily: HANDWRITTEN_TEXT_FONT,
  },
  bubbleUserWrap: { width: "100%", alignItems: "flex-end", marginTop: 1 },
  bubbleAssistantWrap: { width: "100%", alignItems: "flex-start", marginTop: 1 },
  bubbleUser: {
    maxWidth: "80%",
    alignSelf: "flex-end",
    flexShrink: 1,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: "#ECECEC",
    overflow: "hidden",
  },
  userAttachmentStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 6,
    marginBottom: 8,
  },
  userAttachmentImage: {
    width: 74,
    height: 74,
    borderRadius: 10,
    backgroundColor: "#d4d4d4",
  },
  // 探索中状态样式
  exploringStatusWrap: {
    width: "100%",
    alignItems: "flex-start",
    paddingTop: 2,
    paddingBottom: 0,
  },
  exploringThinkingText: {
    color: "#b6aea2",
    fontSize: 11,
    lineHeight: 14,
    fontFamily: FONT_UI_MEDIUM,
    letterSpacing: 0.1,
    minHeight: 14,
  },
  exploringStatusCard: {
    width: "96%",
    maxWidth: "96%",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    paddingVertical: 3,
    paddingHorizontal: 2,
    gap: 5,
  },
  exploringStatusHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  exploringStatusTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  exploringStatusTitle: {
    color: "#4f463a",
    fontSize: 12.5,
    lineHeight: 16,
    fontFamily: FONT_UI_MEDIUM,
  },
  exploringStatusText: {
    color: "#5d5347",
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: FONT_UI_MEDIUM,
    flexShrink: 1,
  },
  exploringStatusMeta: {
    color: "#938778",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: FONT_UI_REGULAR,
  },
  exploringStatusListCard: {
    width: "96%",
    marginTop: 4,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 2,
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    gap: 7,
  },
  eventDiffList: {
    gap: 10,
    marginTop: 4,
    paddingLeft: 12,
  },
  eventDiffBlock: {
    gap: 8,
    paddingLeft: 12,
  },
  eventDiffHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  eventDiffPath: {
    flex: 1,
    color: "#10A37F",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: FONT_UI_REGULAR,
  },
  eventDiffCodeWindow: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2d2d2d",
    backgroundColor: "#2d2d2d",
    overflow: "hidden",
  },
  eventDiffCodeWrap: {
    maxHeight: 280,
  },
  eventDiffCodeCanvas: {
    minWidth: "100%",
    paddingVertical: 6,
  },
  eventDiffRow: {
    minHeight: 20,
    paddingHorizontal: 8,
    paddingVertical: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  eventDiffRowContext: {
    backgroundColor: "transparent",
  },
  eventDiffRowAdd: {
    backgroundColor: "rgba(31,138,91,0.10)",
  },
  eventDiffRowDelete: {
    backgroundColor: "rgba(182,91,91,0.10)",
  },
  eventDiffRowHunk: {
    backgroundColor: "#2d2d2d",
  },
  eventDiffRowNote: {
    backgroundColor: "#2d2d2d",
  },
  eventDiffLineNumber: {
    width: 28,
    textAlign: "right",
    color: "#b2a591",
    fontSize: 10,
    lineHeight: 16,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  eventDiffLineNumberMuted: {
    color: "transparent",
  },
  eventDiffMarker: {
    width: 10,
    color: "#9d907f",
    fontSize: 10,
    lineHeight: 16,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  eventDiffCodeText: {
    color: "#4b453d",
    fontSize: 11,
    lineHeight: 16,
    flexShrink: 0,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  disclosureChevron: {
    width: 11,
    height: 11,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transform: [{ rotate: "-90deg" }],
  },
  disclosureChevronExpanded: {
    transform: [{ rotate: "0deg" }],
  },
  disclosureChevronLineLeft: {
    position: "absolute",
    width: 4.5,
    height: 1,
    borderRadius: 999,
    backgroundColor: "#9da5b4",
    transform: [{ translateX: -1.2 }, { rotate: "45deg" }],
  },
  disclosureChevronLineRight: {
    position: "absolute",
    width: 4.5,
    height: 1,
    borderRadius: 999,
    backgroundColor: "#9da5b4",
    transform: [{ translateX: 1.2 }, { rotate: "-45deg" }],
  },
} satisfies MobileNamedStyles;
